### ISSUE TITLE
error in composer

### ISSUE THREAD

**Issue by kalindigital** [TheWebSolver/tws-license-manager-client#10]
I edited the composer.json file and this message appears in the terminal

"Root package 'thewebsolver/tws-license-manager-client' cannot require itself in its composer.json
  Did you accidentally name your root package after an external package?"

**Comment by hsehszroc** [comment]
> "Root package 'thewebsolver/tws-license-manager-client' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?"

This is an obvious error if you are trying to require the package in it's own composer file. You'll need to require this package as dependency to your own composer file.

Let me know if there is any other query.
