### ISSUE TITLE
Mabe PHP < 7.1 issue?

### ISSUE THREAD

**Issue by yonifre** [TheWebSolver/tws-license-manager-client#7]
When I try to use PHP 5.6 I get this notice:   

2021/11/14 14:17:31 [error] 27406#0: *250323 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in XX...Includes/API/Manager.php on line 268

**Comment by hsehszroc** [comment]
@yonifre thanks for the update.
Unfortunately, it is not tested on that version of PHP.
