### ISSUE TITLE
Logical Error

### ISSUE THREAD

**Issue by vijayhardaha** [TheWebSolver/tws-license-manager-client#8]
Can you review this:
Filename: `Includes/API/Manager.php`
Line: 1611
Code: `if ( isset( $data[ $this->dirname ][ $key ] ) && 'email' === $data[ $this->dirname ][ $key ] )`

Issue: `'email' === $data[ $this->dirname ][ $key ]` how will this condition will ever work? `'email' === $key` should be there `$data[ $this->dirname ][ $key ]` will return the email address not the `email` key, same goes with `order_id` and `slug` condition.

**Comment by hsehszroc** [comment]
@vijayhardaha Thanks for reporting this error. It has now been fixed with commit a635b08.
